apiVersion: v1
kind: Service
metadata:
  name: mclientui
spec:
  selector:
    app: microservice-clientui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-clientui
  template:
    metadata:
      labels:
        app: microservice-clientui
    spec:
      containers:
        - name: microservice-clientui
          image: elganiesta/clientui:17
          ports:
            - name: http
              containerPort: 8080
